/**
 * generated by Xtext 2.13.0
 */
package org.example.eis;

import org.example.eis.AbstractEisRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EisRuntimeModule extends AbstractEisRuntimeModule {
}
