/**
 * generated by Xtext 2.13.0
 */
package org.example.eis.eis;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EFloat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.eis.eis.EFloat#getValue <em>Value</em>}</li>
 *   <li>{@link org.example.eis.eis.EFloat#getValueOfDecimal <em>Value Of Decimal</em>}</li>
 * </ul>
 *
 * @see org.example.eis.eis.EisPackage#getEFloat()
 * @model
 * @generated
 */
public interface EFloat extends Idiom
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see org.example.eis.eis.EisPackage#getEFloat_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link org.example.eis.eis.EFloat#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Value Of Decimal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value Of Decimal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value Of Decimal</em>' attribute.
   * @see #setValueOfDecimal(int)
   * @see org.example.eis.eis.EisPackage#getEFloat_ValueOfDecimal()
   * @model
   * @generated
   */
  int getValueOfDecimal();

  /**
   * Sets the value of the '{@link org.example.eis.eis.EFloat#getValueOfDecimal <em>Value Of Decimal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value Of Decimal</em>' attribute.
   * @see #getValueOfDecimal()
   * @generated
   */
  void setValueOfDecimal(int value);

} // EFloat
