/**
 * generated by Xtext 2.14.0
 */
package org.example.eis.eis;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inout</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.eis.eis.Inout#getName <em>Name</em>}</li>
 *   <li>{@link org.example.eis.eis.Inout#getInoutVariables <em>Inout Variables</em>}</li>
 * </ul>
 *
 * @see org.example.eis.eis.EisPackage#getInout()
 * @model
 * @generated
 */
public interface Inout extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.eis.eis.EisPackage#getInout_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.eis.eis.Inout#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Inout Variables</b></em>' containment reference list.
   * The list contents are of type {@link org.example.eis.eis.Variables}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inout Variables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inout Variables</em>' containment reference list.
   * @see org.example.eis.eis.EisPackage#getInout_InoutVariables()
   * @model containment="true"
   * @generated
   */
  EList<Variables> getInoutVariables();

} // Inout
