/**
 * generated by Xtext 2.13.0
 */
package org.example.eis.eis;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.eis.eis.Model#getProject_name <em>Project name</em>}</li>
 *   <li>{@link org.example.eis.eis.Model#getPlc_name <em>Plc name</em>}</li>
 *   <li>{@link org.example.eis.eis.Model#getTestcases <em>Testcases</em>}</li>
 * </ul>
 *
 * @see org.example.eis.eis.EisPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Project name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Project name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Project name</em>' attribute.
   * @see #setProject_name(String)
   * @see org.example.eis.eis.EisPackage#getModel_Project_name()
   * @model
   * @generated
   */
  String getProject_name();

  /**
   * Sets the value of the '{@link org.example.eis.eis.Model#getProject_name <em>Project name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Project name</em>' attribute.
   * @see #getProject_name()
   * @generated
   */
  void setProject_name(String value);

  /**
   * Returns the value of the '<em><b>Plc name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Plc name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plc name</em>' attribute.
   * @see #setPlc_name(String)
   * @see org.example.eis.eis.EisPackage#getModel_Plc_name()
   * @model
   * @generated
   */
  String getPlc_name();

  /**
   * Sets the value of the '{@link org.example.eis.eis.Model#getPlc_name <em>Plc name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plc name</em>' attribute.
   * @see #getPlc_name()
   * @generated
   */
  void setPlc_name(String value);

  /**
   * Returns the value of the '<em><b>Testcases</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Testcases</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Testcases</em>' attribute list.
   * @see org.example.eis.eis.EisPackage#getModel_Testcases()
   * @model unique="false"
   * @generated
   */
  EList<String> getTestcases();

} // Model
