/**
 * generated by Xtext 2.13.0
 */
package org.example.eis.eis;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PLC Name</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.eis.eis.EisPackage#getPLCName()
 * @model
 * @generated
 */
public interface PLCName extends EisType
{
} // PLCName
