/**
 * generated by Xtext 2.14.0
 */
package org.xtext.eis.ui.outline;

import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.eclipse.xtext.ui.editor.outline.impl.EObjectNode;
import org.xtext.eis.eis.AssertionBlock;
import org.xtext.eis.eis.DefineBlock;
import org.xtext.eis.eis.DirectionBlock;
import org.xtext.eis.eis.EisModel;
import org.xtext.eis.eis.Testcase;
import org.xtext.eis.eis.TeststepBlock;
import org.xtext.eis.eis.Variable;
import org.xtext.eis.eis.Variables;

@SuppressWarnings("all")
public class EisOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final Variables v) {
    boolean _xifexpression = false;
    if ((v instanceof Variable)) {
      _xifexpression = true;
    } else {
      _xifexpression = false;
    }
    return _xifexpression;
  }
  
  public boolean _isLeaf(final TeststepBlock t) {
    return true;
  }
  
  public boolean _isLeaf(final AssertionBlock a) {
    return true;
  }
  
  public void _createChildren(final DocumentRootNode outlineNode, final EisModel eisModel) {
    final EList<Testcase> testcases = eisModel.getTestcases();
    for (final Testcase e : testcases) {
      this.createNode(outlineNode, e);
    }
  }
  
  public void _createChildren(final EObjectNode testcaseNode, final Testcase testcase) {
    DefineBlock _define = null;
    if (testcase!=null) {
      _define=testcase.getDefine();
    }
    DirectionBlock _direction = null;
    if (_define!=null) {
      _direction=_define.getDirection();
    }
    final DirectionBlock direction = _direction;
    DefineBlock _define_1 = null;
    if (testcase!=null) {
      _define_1=testcase.getDefine();
    }
    EList<TeststepBlock> _teststeps = null;
    if (_define_1!=null) {
      _teststeps=_define_1.getTeststeps();
    }
    final EList<TeststepBlock> teststeps = _teststeps;
    this.createChildren(testcaseNode, direction);
    for (final TeststepBlock e : teststeps) {
      this.createChildren(testcaseNode, e);
    }
  }
}
