/*
 * generated by Xtext 2.14.0
 */
package org.example.define.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.example.define.ui.internal.DefineActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DefineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DefineActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DefineActivator activator = DefineActivator.getInstance();
		return activator != null ? activator.getInjector(DefineActivator.ORG_EXAMPLE_DEFINE_DEFINE) : null;
	}

}
