/**
 * generated by Xtext 2.13.0
 */
package org.example.eis.eis.impl;

import org.eclipse.emf.ecore.EClass;

import org.example.eis.eis.EisPackage;
import org.example.eis.eis.TiaProjectName;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tia Project Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TiaProjectNameImpl extends EisTypeImpl implements TiaProjectName
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TiaProjectNameImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EisPackage.Literals.TIA_PROJECT_NAME;
  }

} //TiaProjectNameImpl
