/**
 * generated by Xtext 2.13.0
 */
package org.example.define.define.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.example.define.define.DefinePackage;
import org.example.define.define.EFloat;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EFloat</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.define.define.impl.EFloatImpl#getValue <em>Value</em>}</li>
 *   <li>{@link org.example.define.define.impl.EFloatImpl#getValueOfDecimal <em>Value Of Decimal</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFloatImpl extends IdiomImpl implements EFloat
{
  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final int VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected int value = VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getValueOfDecimal() <em>Value Of Decimal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueOfDecimal()
   * @generated
   * @ordered
   */
  protected static final int VALUE_OF_DECIMAL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getValueOfDecimal() <em>Value Of Decimal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueOfDecimal()
   * @generated
   * @ordered
   */
  protected int valueOfDecimal = VALUE_OF_DECIMAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFloatImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DefinePackage.Literals.EFLOAT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(int newValue)
  {
    int oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinePackage.EFLOAT__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValueOfDecimal()
  {
    return valueOfDecimal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValueOfDecimal(int newValueOfDecimal)
  {
    int oldValueOfDecimal = valueOfDecimal;
    valueOfDecimal = newValueOfDecimal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DefinePackage.EFLOAT__VALUE_OF_DECIMAL, oldValueOfDecimal, valueOfDecimal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DefinePackage.EFLOAT__VALUE:
        return getValue();
      case DefinePackage.EFLOAT__VALUE_OF_DECIMAL:
        return getValueOfDecimal();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DefinePackage.EFLOAT__VALUE:
        setValue((Integer)newValue);
        return;
      case DefinePackage.EFLOAT__VALUE_OF_DECIMAL:
        setValueOfDecimal((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DefinePackage.EFLOAT__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
      case DefinePackage.EFLOAT__VALUE_OF_DECIMAL:
        setValueOfDecimal(VALUE_OF_DECIMAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DefinePackage.EFLOAT__VALUE:
        return value != VALUE_EDEFAULT;
      case DefinePackage.EFLOAT__VALUE_OF_DECIMAL:
        return valueOfDecimal != VALUE_OF_DECIMAL_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (value: ");
    result.append(value);
    result.append(", valueOfDecimal: ");
    result.append(valueOfDecimal);
    result.append(')');
    return result.toString();
  }

} //EFloatImpl
