/**
 * generated by Xtext 2.13.0
 */
package org.example.define.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.define.DefineRuntimeModule;
import org.example.define.DefineStandaloneSetup;
import org.example.define.ide.DefineIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DefineIdeSetup extends DefineStandaloneSetup {
  @Override
  public Injector createInjector() {
    DefineRuntimeModule _defineRuntimeModule = new DefineRuntimeModule();
    DefineIdeModule _defineIdeModule = new DefineIdeModule();
    return Guice.createInjector(Modules2.mixin(_defineRuntimeModule, _defineIdeModule));
  }
}
