/**
 * generated by Xtext 2.13.0
 */
package org.example.define.ide;

import org.example.define.ide.AbstractDefineIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DefineIdeModule extends AbstractDefineIdeModule {
}
