/**
 * generated by Xtext 2.14.0
 */
package org.xtext.eis.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.eis.ui.AbstractEisUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EisUiModule extends AbstractEisUiModule {
  public EisUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
