/**
 * generated by Xtext 2.13.0
 */
package org.example.define.define;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inout</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.define.define.Inout#getInoutVariables <em>Inout Variables</em>}</li>
 * </ul>
 *
 * @see org.example.define.define.DefinePackage#getInout()
 * @model
 * @generated
 */
public interface Inout extends EObject
{
  /**
   * Returns the value of the '<em><b>Inout Variables</b></em>' containment reference list.
   * The list contents are of type {@link org.example.define.define.Variable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inout Variables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inout Variables</em>' containment reference list.
   * @see org.example.define.define.DefinePackage#getInout_InoutVariables()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getInoutVariables();

} // Inout
