/**
 * generated by Xtext 2.13.0
 */
package org.example.define.define;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.define.define.DefinePackage#getInt()
 * @model
 * @generated
 */
public interface Int extends Types
{
} // Int
