/**
 * generated by Xtext 2.14.0
 */
package org.example.define.define;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Udt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.define.define.Udt#getUdtType <em>Udt Type</em>}</li>
 *   <li>{@link org.example.define.define.Udt#getUdtVariables <em>Udt Variables</em>}</li>
 * </ul>
 *
 * @see org.example.define.define.DefinePackage#getUdt()
 * @model
 * @generated
 */
public interface Udt extends Variables
{
  /**
   * Returns the value of the '<em><b>Udt Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Udt Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Udt Type</em>' containment reference.
   * @see #setUdtType(UdtType)
   * @see org.example.define.define.DefinePackage#getUdt_UdtType()
   * @model containment="true"
   * @generated
   */
  UdtType getUdtType();

  /**
   * Sets the value of the '{@link org.example.define.define.Udt#getUdtType <em>Udt Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Udt Type</em>' containment reference.
   * @see #getUdtType()
   * @generated
   */
  void setUdtType(UdtType value);

  /**
   * Returns the value of the '<em><b>Udt Variables</b></em>' containment reference list.
   * The list contents are of type {@link org.example.define.define.Variables}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Udt Variables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Udt Variables</em>' containment reference list.
   * @see org.example.define.define.DefinePackage#getUdt_UdtVariables()
   * @model containment="true"
   * @generated
   */
  EList<Variables> getUdtVariables();

} // Udt
