/**
 * generated by Xtext 2.14.0
 */
package org.example.define.define;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Udt Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.define.define.UdtType#getUdtTypeName <em>Udt Type Name</em>}</li>
 * </ul>
 *
 * @see org.example.define.define.DefinePackage#getUdtType()
 * @model
 * @generated
 */
public interface UdtType extends EObject
{
  /**
   * Returns the value of the '<em><b>Udt Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Udt Type Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Udt Type Name</em>' attribute.
   * @see #setUdtTypeName(String)
   * @see org.example.define.define.DefinePackage#getUdtType_UdtTypeName()
   * @model
   * @generated
   */
  String getUdtTypeName();

  /**
   * Sets the value of the '{@link org.example.define.define.UdtType#getUdtTypeName <em>Udt Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Udt Type Name</em>' attribute.
   * @see #getUdtTypeName()
   * @generated
   */
  void setUdtTypeName(String value);

} // UdtType
